### ISSUE TITLE
 Dev Task # 7 -Create Database models from ERD

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#10]
As a developer, I can setup my models.py file to create the structure of my database tables.

### Acceptance Criteria

AC1: Successfully created CoinPilot ERD.
AC2: Added models to models.py.
AC3: Imported relevant Django/Cloudinary models.

### Tasks

- [ ]  Import Django/Cloudinary models
- [ ]  Add user model
- [ ]  Add dog model
- [ ]  Add booking model
- [ ]  Add photo model
- [ ]  Add feedback model
