### ISSUE TITLE
Dev Task # 6 -Create Database models from ERD

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#10]
As a developer, I can setup my models.py file to create the structure of my database tables.

### Acceptance Criteria

1. Successfully create CoinPilot ERD.
2. Add models to models.py.
3. Import relevant Django/Cloudinary models.

### Tasks

- [x]  Create an ERD
- [x] Import Django/Cloudinary models
- [x]  Add user model
