### ISSUE TITLE
Dev Task #11 - Tailwind SetUp

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#11]
As a developer, I can add and configure Tailwind CSS in my development environment so that I can create my website's frontend.

### Acceptance Criteria

AC1: Successful install of Tailwind as per Tailwind docs.
AC2: Successful configuration of Tailwind in base CSS and HTML files.

### Tasks

- [ ]  Install Tailwind following docs
- [ ]  Configure paths to link Tailwind with base CSS and HTML files
- [ ]  Complete the Tailwind build process with the correct file paths
- [ ]  Confirm Tailwind install using 'npm ls'
