### ISSUE TITLE
User Logout

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#13]
As a user, I want to be able to log out of the application, so that my account remains secure.

### Acceptance Criteria:

1. The user should have a clear way to initiate the logout process (e.g., a logout button or link)
2. Upon successful logout, the user's authentication status should be revoked
3. The user should be redirected to the login page or a public area of the application
4. Any sensitive data or sessions associated with the user should be cleared or invalidated

### Tasks

- [x] - Create a logout button or link in the user interface
- [x] - Implement a logout function or view in the backend
- [x] - Revoke the user's authentication token or session cookie
- [x] - Clear any sensitive data or sessions associated with the user
- [x] - Redirect the user to the login page or a public area of the application
- [x] - Display a confirmation message or notification upon successful logout
