### ISSUE TITLE
Dev Task #2: Create Django Project

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#2]
As a developer, I want to set up the Django project so that I can start building the application

### Acceptance Criteria

AC1: Django project is created with the appropriate project structure
AC2: Portfolio management app is created
AC3: Django settings are configured for development environment

### Tasks

- [ ]  Create the Django project CoinPilot directory
- [ ]  Create the portfolio management app
- [ ]  Add it to the list of INSTALLED_APPS
- [ ]  Migrate the changes to the database
- [ ]  Add 8000 port url to ALLOWED_HOSTS
- [ ]  python3 manage.py runserver to test

**Comment by equaynor** [comment]
For some reason site works without adding Port 8000 to ALLOWED_HOSTS list, but not when it is added. Maybe the reason is the conda env?
