### ISSUE TITLE
 Dev Task #2 - Create Django Project

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#2]
As a developer, I can create the Django project and app so that I can set up the database.

### Acceptance Criteria

1. Create the Django project CoinPilot directory
2. Create the app structure

### Tasks

- [x]  Create the Django project CoinPilot directory
- [x]  Create the account app
- [x] Create the portfolio app
- [x] Create the trades app
- [x] Create the cryptocurrency app
- [x]  Add it to the list of INSTALLED_APPS
- [x]  Migrate the changes to the database
- [x]  Add 8000 port url to ALLOWED_HOSTS
- [x]  python3 manage.py runserver to test
