### ISSUE TITLE
Dev Task #5 - Set up Cloudinary

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#5]
As a developer, I can set up a Cloudinary account and connect it to my project so that I can upload any images to be stored.

### Acceptance Criteria

AC1: Successful connection between CoinPilot and Cloudinary.
AC2: Successful connection between Cloudinary and Heroku.
AC3: Configuration of Media and Static files.

###Tasks

- [ ]  Add Cloudinary API environment variable to env.py and Heroku
- [ ]  Set DISABLE_COLLECTSTATIC on Heroku (remove before deployment)
- [ ]  Add Cloudinary libraries to INSTALLED_APPS in settings.py
- [ ]  In settings.py set Cloudinary as storage for media and static files
