### ISSUE TITLE
Dev Task #6 - Deployment

### ISSUE THREAD

**Issue by equaynor** [equaynor/CoinPilot#6]
As a developer, I can instruct Django to deploy the project successfully.

### Acceptance Criteria

AC1: Inform Django where the templates are stored.
AC2: Inform Django where the project is being hosted.
AC3: Successful first deployment.

### Tasks

- [ ]  Set up the templates directory in settings.py
- [ ]  Add Heroku host name into ALLOWED_HOSTS in settings.py
- [ ]  Create the media, static and templates folders in the top level directory
- [ ]  Create a Procfile and add project name
- [ ]  Save, add, commit, push
- [ ]  Deploy
